
import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./context/authProviders";
import { Navbar } from "@/components/mycomponents/navbar";
import Footer from "@/components/mycomponents/footer";
import { Toaster } from "@/components/ui/sonner";



export const metadata: Metadata = {
  title: "COURSE-MATE",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html suppressHydrationWarning
    >
      <body>
        <AuthProvider>
          <Navbar />

          {/* <ThemeProvider > */}
          
            {children}
          
          <Toaster />
          <Footer />
          {/* </ThemeProvider> */}
        </AuthProvider>
      </body>


    </html >
  );
}
